
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftMULTDIVrightPOWDIV LPAREN MINUS MULT NEWLINE NUMBER PLUS POW RPARENinput : line\n                 | input lineline : expr NEWLINEline : error NEWLINEexpr : simple_exprexpr : expr PLUS exprexpr : expr MINUS exprexpr : expr MULT exprexpr : expr DIV exprsimple_expr : power_exprpower_expr : atompower_expr : atom POW exponentatom : NUMBER_CHANGEDatom : LPAREN expr RPARENexponent : EXP_SIMPLEexponent : LPAREN EXP_COMPLEX RPARENNUMBER_CHANGED : NUMBERNUMBER_CHANGED : MINUS NUMBEREXP_SIMPLE : NUMBEREXP_SIMPLE : MINUS NUMBEREXP_COMPLEX : EXP_SIMPLEEXP_COMPLEX : EXP_COMPLEX PLUS EXP_SIMPLEEXP_COMPLEX : EXP_COMPLEX MINUS EXP_SIMPLEEXP_COMPLEX : EXP_COMPLEX MULT EXP_SIMPLEEXP_COMPLEX : EXP_COMPLEX DIV EXP_SIMPLE'
    
_lr_action_items = {'error':([0,1,2,12,13,18,],[4,4,-1,-2,-3,-4,]),'LPAREN':([0,1,2,10,12,13,14,15,16,17,18,20,],[10,10,-1,10,-2,-3,10,10,10,10,-4,28,]),'NUMBER':([0,1,2,6,10,12,13,14,15,16,17,18,20,28,30,36,37,38,39,],[11,11,-1,19,11,-2,-3,11,11,11,11,-4,29,29,34,29,29,29,29,]),'MINUS':([0,1,2,3,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,31,32,33,34,35,36,37,38,39,40,41,42,43,],[6,6,-1,15,-5,-10,-11,-13,6,-17,-2,-3,6,6,6,6,-4,-18,30,15,-6,-7,-8,-9,-12,-15,30,-19,-14,37,-21,-20,-16,30,30,30,30,-22,-23,-24,-25,]),'$end':([1,2,12,13,18,],[0,-1,-2,-3,-4,]),'NEWLINE':([3,4,5,7,8,9,11,19,22,23,24,25,26,27,29,31,34,35,],[13,18,-5,-10,-11,-13,-17,-18,-6,-7,-8,-9,-12,-15,-19,-14,-20,-16,]),'PLUS':([3,5,7,8,9,11,19,21,22,23,24,25,26,27,29,31,32,33,34,35,40,41,42,43,],[14,-5,-10,-11,-13,-17,-18,14,-6,-7,-8,-9,-12,-15,-19,-14,36,-21,-20,-16,-22,-23,-24,-25,]),'MULT':([3,5,7,8,9,11,19,21,22,23,24,25,26,27,29,31,32,33,34,35,40,41,42,43,],[16,-5,-10,-11,-13,-17,-18,16,16,16,-8,-9,-12,-15,-19,-14,38,-21,-20,-16,-22,-23,-24,-25,]),'DIV':([3,5,7,8,9,11,19,21,22,23,24,25,26,27,29,31,32,33,34,35,40,41,42,43,],[17,-5,-10,-11,-13,-17,-18,17,17,17,-8,-9,-12,-15,-19,-14,39,-21,-20,-16,-22,-23,-24,-25,]),'RPAREN':([5,7,8,9,11,19,21,22,23,24,25,26,27,29,31,32,33,34,35,40,41,42,43,],[-5,-10,-11,-13,-17,-18,31,-6,-7,-8,-9,-12,-15,-19,-14,35,-21,-20,-16,-22,-23,-24,-25,]),'POW':([8,9,11,19,31,],[20,-13,-17,-18,-14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'input':([0,],[1,]),'line':([0,1,],[2,12,]),'expr':([0,1,10,14,15,16,17,],[3,3,21,22,23,24,25,]),'simple_expr':([0,1,10,14,15,16,17,],[5,5,5,5,5,5,5,]),'power_expr':([0,1,10,14,15,16,17,],[7,7,7,7,7,7,7,]),'atom':([0,1,10,14,15,16,17,],[8,8,8,8,8,8,8,]),'NUMBER_CHANGED':([0,1,10,14,15,16,17,],[9,9,9,9,9,9,9,]),'exponent':([20,],[26,]),'EXP_SIMPLE':([20,28,36,37,38,39,],[27,33,40,41,42,43,]),'EXP_COMPLEX':([28,],[32,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> input","S'",1,None,None,None),
  ('input -> line','input',1,'p_input','parser.py',82),
  ('input -> input line','input',2,'p_input','parser.py',83),
  ('line -> expr NEWLINE','line',2,'p_line_expr','parser.py',87),
  ('line -> error NEWLINE','line',2,'p_line_error','parser.py',93),
  ('expr -> simple_expr','expr',1,'p_expr_simple','parser.py',102),
  ('expr -> expr PLUS expr','expr',3,'p_expr_plus','parser.py',106),
  ('expr -> expr MINUS expr','expr',3,'p_expr_minus','parser.py',111),
  ('expr -> expr MULT expr','expr',3,'p_expr_mult','parser.py',116),
  ('expr -> expr DIV expr','expr',3,'p_expr_div','parser.py',121),
  ('simple_expr -> power_expr','simple_expr',1,'p_simple_expr','parser.py',133),
  ('power_expr -> atom','power_expr',1,'p_power_expr_atom','parser.py',137),
  ('power_expr -> atom POW exponent','power_expr',3,'p_power_expr_pow','parser.py',141),
  ('atom -> NUMBER_CHANGED','atom',1,'p_atom_number','parser.py',156),
  ('atom -> LPAREN expr RPAREN','atom',3,'p_atom_paren','parser.py',161),
  ('exponent -> EXP_SIMPLE','exponent',1,'p_exponent_simple','parser.py',165),
  ('exponent -> LPAREN EXP_COMPLEX RPAREN','exponent',3,'p_exponent_complex','parser.py',169),
  ('NUMBER_CHANGED -> NUMBER','NUMBER_CHANGED',1,'p_NUMBER_CHANGED_number','parser.py',173),
  ('NUMBER_CHANGED -> MINUS NUMBER','NUMBER_CHANGED',2,'p_NUMBER_CHANGED_uminus','parser.py',177),
  ('EXP_SIMPLE -> NUMBER','EXP_SIMPLE',1,'p_EXP_SIMPLE_number','parser.py',181),
  ('EXP_SIMPLE -> MINUS NUMBER','EXP_SIMPLE',2,'p_EXP_SIMPLE_uminus','parser.py',186),
  ('EXP_COMPLEX -> EXP_SIMPLE','EXP_COMPLEX',1,'p_EXP_COMPLEX_simple','parser.py',191),
  ('EXP_COMPLEX -> EXP_COMPLEX PLUS EXP_SIMPLE','EXP_COMPLEX',3,'p_EXP_COMPLEX_plus','parser.py',195),
  ('EXP_COMPLEX -> EXP_COMPLEX MINUS EXP_SIMPLE','EXP_COMPLEX',3,'p_EXP_COMPLEX_minus','parser.py',200),
  ('EXP_COMPLEX -> EXP_COMPLEX MULT EXP_SIMPLE','EXP_COMPLEX',3,'p_EXP_COMPLEX_mult','parser.py',205),
  ('EXP_COMPLEX -> EXP_COMPLEX DIV EXP_SIMPLE','EXP_COMPLEX',3,'p_EXP_COMPLEX_div','parser.py',210),
]
